# TODO: PRE-CALCULATE PRIORITY VECTOR: VS_AGGREGATED_PLAN_TIMES * VS_NUM_DIRECTIVE_PRODUCTS / VS_DIRECTIVE_TERMS
# TODO: SOLVE BY PRIORITY VALUES: THE HIGHER PRIORITY THAN TO SOLVE IN THE FIRST PLACE (JUST SORT T_I_L ( (№2 formula)) by this index)


def center_model():
    pass
